Fix source names to differ
* Same names for c and cpp source files (except ending) causes
  intermediate files to have the same name, e.g. test_empty.s.
  This causes strange errors like 'undefined reference to _start',
  if the cpp intermediate file gets generated, before the as is
  called for the c intermediate file.
* cpp files have _cc added to their name to fix behavior.

Change-Id: Ia16725f5603c0382a0ecbb4acbdb6c02b79e77f0